name: Web Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install CLIs
      run: npm run ci-setup
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build-web
    - name: Publish to Zeit Now
      run: now --prod --token ${{ secrets.zeit_now }}
    - name: Publish to Expo
      env:
        EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
      run: |
        npx expo login --non-interactive -u ${{ secrets.EXPO_USERNAME }}
        npx expo publish

